package engine

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"

	"github.com/stephenc/git-scaffold/internal/config"
	"github.com/stephenc/git-scaffold/internal/gitx"
	"github.com/stephenc/git-scaffold/internal/materialize"
)

// tomlTarget is the serialized shape of a freshly initialized target
// configuration (§4). Overrides are generated by init --existing (§33);
// further overrides are added by hand later.
type tomlTarget struct {
	Scaffold struct {
		Version int `toml:"version"`
	} `toml:"scaffold"`
	Source struct {
		Git string `toml:"git"`
		Ref string `toml:"ref,omitempty"`
	} `toml:"source"`
	Args      map[string]string       `toml:"args,omitempty"`
	Overrides map[string]tomlOverride `toml:"overrides,omitempty"`
}

type tomlOverride struct {
	Strategy string   `toml:"strategy"`
	Patches  []string `toml:"patches"`
}

// Init implements `git scaffold init` (§33): create the target
// configuration, resolve the source, materialize, and write the lock.
// With existing, managed files already present with differing text content
// are adopted as text-patch overrides instead of being overwritten; the
// pre-existing bytes are left untouched. Nothing is written until the
// complete result has been validated.
func Init(dir string, out io.Writer, url, ref string, args map[string]string, existing, force bool) error {
	root, err := gitx.WorktreeRoot(dir)
	if err != nil {
		return err
	}
	cfgPath := filepath.Join(root, metaDir, "config.toml")
	if _, err := os.Stat(cfgPath); err == nil {
		return fmt.Errorf("%s already exists", configName)
	}
	src, err := gitx.Open(url)
	if err != nil {
		return err
	}
	sha, err := src.ResolveRef(ref)
	if err != nil {
		return err
	}
	cfg := &config.TargetConfig{
		SourceGit: url,
		SourceRef: ref,
		Args:      args,
		Overrides: map[string]config.Override{},
	}
	t := &target{root: root, cfg: cfg, src: src}
	tree, err := t.materializeAt(sha)
	if err != nil {
		return err
	}

	writes := map[string][]byte{}
	patchFiles := map[string][]byte{} // keyed relative to .git-scaffold/
	var created, adopted, overwritten []string
	if existing {
		created, adopted, overwritten, err = t.adoptExisting(tree, sha, writes, patchFiles, force)
		if err != nil {
			return err
		}
	} else {
		cs, err := conflicts(root, tree, nil, nil)
		if err != nil {
			return err
		}
		if len(cs) > 0 && !force {
			return conflictError(cs)
		}
		for _, p := range sortedKeys(tree) {
			// A pre-existing identical file is neither created nor changed:
			// leave it alone and keep it out of the report.
			w, ok, err := readWorking(root, p)
			if err != nil {
				return err
			}
			if ok && bytes.Equal(w, tree[p]) {
				continue
			}
			writes[p] = tree[p]
			created = append(created, p)
		}
	}

	var enc tomlTarget
	enc.Scaffold.Version = config.Version
	enc.Source.Git = url
	enc.Source.Ref = ref
	enc.Args = args
	if len(cfg.Overrides) > 0 {
		enc.Overrides = map[string]tomlOverride{}
		for p, o := range cfg.Overrides {
			enc.Overrides[p] = tomlOverride{Strategy: o.Strategy, Patches: o.Patches}
		}
	}
	var buf bytes.Buffer
	if err := toml.NewEncoder(&buf).Encode(enc); err != nil {
		return err
	}
	buf.WriteByte('\n')
	if err := os.MkdirAll(filepath.Join(root, metaDir), 0o755); err != nil {
		return err
	}
	if err := writeFileAtomic(cfgPath, buf.Bytes()); err != nil {
		return err
	}
	for rel, data := range patchFiles {
		writes[metaDir+"/"+rel] = data
	}
	if err := commit(root, writes, nil, sha); err != nil {
		return err
	}
	for _, p := range created {
		fmt.Fprintf(out, "A %s\n", p)
	}
	for _, p := range overwritten {
		fmt.Fprintf(out, "M %s\n", p)
	}
	for _, p := range adopted {
		fmt.Fprintf(out, "P %s\n", p)
	}
	msg := fmt.Sprintf("initialized scaffold from %s at %s", url, short(sha))
	if n := len(adopted); n > 0 {
		plural := "s"
		if n == 1 {
			plural = ""
		}
		msg += fmt.Sprintf("; adopted %d existing file%s as text patches", n, plural)
	}
	io.WriteString(out, status(true, msg))
	return nil
}

// adoptExisting implements the --existing flow of init (§33): compare each
// expected managed file with the worktree, materialize missing files, leave
// identical files alone, and capture text differences as verified text-patch
// overrides stored under patches/. Differing binary-looking files cannot be
// adopted; without force they cause a refusal, with force they are
// overwritten. It fills writes and patchFiles, registers overrides on
// t.cfg, and returns the created/adopted/overwritten path lists.
func (t *target) adoptExisting(
	tree map[string][]byte, sha string, writes, patchFiles map[string][]byte, force bool,
) (created, adopted, overwritten []string, err error) {
	expect := map[string][]byte{} // the worktree content after init
	usedNames := map[string]bool{}
	var binaries []string
	for _, p := range sortedKeys(tree) {
		w, ok, err := readWorking(t.root, p)
		if err != nil {
			return nil, nil, nil, err
		}
		switch {
		case !ok:
			writes[p] = tree[p]
			created = append(created, p)
			expect[p] = tree[p]
		case bytes.Equal(w, tree[p]):
			expect[p] = tree[p]
		case isBinary(tree[p]) || isBinary(w):
			// §33: no meaningful unified text diff exists; refuse unless
			// force permits overwriting.
			binaries = append(binaries, p)
			writes[p] = tree[p]
			overwritten = append(overwritten, p)
			expect[p] = tree[p]
		default:
			rel := "patches/" + patchName(p, usedNames) + ".patch"
			patch := []byte(unifiedDiff(p, tree[p], w, true))
			// The guarantee (§33) hinges on the generated diff applying
			// through the strict text-patch applier and reproducing the
			// existing bytes exactly; verify before anything is written.
			got, err := materialize.ApplyTextPatch(p, rel, tree[p], patch)
			if err != nil {
				return nil, nil, nil, fmt.Errorf("init --existing: generated patch for %s does not apply: %w", p, err)
			}
			if !bytes.Equal(got, w) {
				return nil, nil, nil, fmt.Errorf(
					"init --existing: generated patch for %s does not reproduce the existing content", p)
			}
			patchFiles[rel] = patch
			t.cfg.Overrides[p] = config.Override{Strategy: config.StrategyTextPatch, Patches: []string{rel}}
			adopted = append(adopted, p)
			expect[p] = w
		}
	}
	if len(binaries) > 0 && !force {
		return nil, nil, nil, fmt.Errorf(
			"binary files differ from the scaffold and cannot be adopted as text patches"+
				" (rerun with --force to overwrite them):\n  %s",
			strings.Join(binaries, "\n  "))
	}
	// Recompute the full materialization with the generated overrides and
	// compare it against the post-init worktree: `check` must pass
	// immediately after init --existing.
	full, err := t.materializeWith(sha, patchFiles)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("init --existing: verification failed: %w", err)
	}
	if len(full) != len(expect) {
		return nil, nil, nil, fmt.Errorf("init --existing: verification failed: managed file set changed")
	}
	for p, want := range expect {
		if !bytes.Equal(full[p], want) {
			return nil, nil, nil, fmt.Errorf(
				"init --existing: verification failed: %s would not match the worktree after init", p)
		}
	}
	return created, adopted, overwritten, nil
}

// patchName mangles a repo-relative path into a unique patch file basename:
// `/` becomes `--`, with a numeric suffix on the rare mangling collision.
func patchName(path string, used map[string]bool) string {
	base := strings.ReplaceAll(path, "/", "--")
	name := base
	for i := 2; used[name]; i++ {
		name = fmt.Sprintf("%s-%d", base, i)
	}
	used[name] = true
	return name
}

// Check implements `git scaffold check` (§34): compare the working tree with
// the expected materialization at the locked commit. It never resolves the
// moving ref. clean reports whether everything matched.
func Check(dir string, out io.Writer) (clean bool, err error) {
	t, err := load(dir)
	if err != nil {
		return false, err
	}
	sha, err := readLock(t.root)
	if err != nil {
		return false, err
	}
	if sha == "" {
		return false, fmt.Errorf("no %s; run `git scaffold apply` first", lockName)
	}
	tree, err := t.materializeAt(sha)
	if err != nil {
		return false, err
	}
	clean = true
	for _, p := range sortedKeys(tree) {
		w, ok, err := readWorking(t.root, p)
		if err != nil {
			return false, err
		}
		switch {
		case !ok:
			fmt.Fprintf(out, "missing:  %s\n", p)
			clean = false
		case !bytes.Equal(w, tree[p]):
			fmt.Fprintf(out, "modified: %s\n", p)
			clean = false
		}
	}
	if clean {
		io.WriteString(out, status(true, "managed files match the locked materialization"))
	} else {
		io.WriteString(out, status(false, "managed files differ from the locked materialization"))
	}
	return clean, nil
}

// Diff implements `git scaffold diff` (§35): unified diff of the working
// tree against the expected materialization (expected content is the `a`
// side). It modifies nothing.
func Diff(dir string, out io.Writer) error {
	t, err := load(dir)
	if err != nil {
		return err
	}
	sha, err := readLock(t.root)
	if err != nil {
		return err
	}
	if sha == "" {
		return fmt.Errorf("no %s; run `git scaffold apply` first", lockName)
	}
	tree, err := t.materializeAt(sha)
	if err != nil {
		return err
	}
	for _, p := range sortedKeys(tree) {
		w, ok, err := readWorking(t.root, p)
		if err != nil {
			return err
		}
		io.WriteString(out, unifiedDiff(p, tree[p], w, ok))
	}
	return nil
}

// Apply implements `git scaffold apply` (§36): make the working tree match
// the locked materialization. It never advances an existing lock; with no
// lock it resolves the configured ref and creates the initial lock.
func Apply(dir string, out io.Writer, force bool) error {
	t, err := load(dir)
	if err != nil {
		return err
	}
	sha, err := readLock(t.root)
	if err != nil {
		return err
	}
	locked := sha != ""
	if !locked {
		if sha, err = t.src.ResolveRef(t.cfg.SourceRef); err != nil {
			return err
		}
	}
	tree, err := t.materializeAt(sha)
	if err != nil {
		return err
	}
	writes := map[string][]byte{}
	created := map[string]bool{}
	for _, p := range sortedKeys(tree) {
		w, ok, err := readWorking(t.root, p)
		if err != nil {
			return err
		}
		if !ok {
			writes[p] = tree[p]
			created[p] = true
		} else if !bytes.Equal(w, tree[p]) {
			writes[p] = tree[p]
		}
	}
	// With an existing lock the expected tree is also the old expected
	// content, so any overwrite here discards a manual edit (§29, §49).
	var old map[string][]byte
	if locked {
		old = tree
	}
	cs, err := conflicts(t.root, writes, nil, old)
	if err != nil {
		return err
	}
	if len(cs) > 0 && !force {
		return conflictError(cs)
	}
	lockSHA := ""
	if !locked {
		lockSHA = sha
	}
	if len(writes) == 0 && lockSHA == "" {
		io.WriteString(out, status(true, "already up to date"))
		return nil
	}
	if err := commit(t.root, writes, nil, lockSHA); err != nil {
		return err
	}
	for _, p := range sortedKeys(writes) {
		if created[p] {
			fmt.Fprintf(out, "A %s\n", p)
		} else {
			fmt.Fprintf(out, "M %s\n", p)
		}
	}
	io.WriteString(out, status(true, "applied "+short(sha)))
	return nil
}

// ErrUpdateFailed is returned by Update after printing a §37-style failure
// report; no target state has been changed.
var ErrUpdateFailed = errors.New("update failed; no files changed")

// Update implements `git scaffold update` (§37): resolve the configured ref
// and transactionally move the working tree and lock from the old
// materialization to the new one (§30-§31).
func Update(dir string, out io.Writer, force bool) error {
	t, err := load(dir)
	if err != nil {
		return err
	}
	oldSHA, err := readLock(t.root)
	if err != nil {
		return err
	}
	if oldSHA == "" {
		return fmt.Errorf("no %s; run `git scaffold apply` first", lockName)
	}
	newSHA, err := t.src.ResolveRef(t.cfg.SourceRef)
	if err != nil {
		return err
	}
	ref := t.cfg.SourceRef
	if ref == "" {
		ref = "HEAD"
	}
	fmt.Fprintf(out, "Updating scaffold\n\nsource: %s\nref:    %s\n\n", t.cfg.SourceGit, ref)
	if newSHA == oldSHA {
		io.WriteString(out, status(true, "already up to date"))
		return nil
	}
	fmt.Fprintf(out, "%s → %s\n\n", short(oldSHA), short(newSHA))

	fail := func(err error) error {
		io.WriteString(out, status(false, err.Error()))
		fmt.Fprintf(out, "\nNo files changed.\n")
		return ErrUpdateFailed
	}
	oldTree, err := t.materializeAt(oldSHA)
	if err != nil {
		return fail(err)
	}
	newTree, err := t.materializeAt(newSHA)
	if err != nil {
		return fail(err)
	}

	writes := map[string][]byte{}
	var added, modified, deleted []string
	for _, p := range sortedKeys(newTree) {
		oldContent, existed := oldTree[p]
		switch {
		case !existed:
			writes[p] = newTree[p]
			added = append(added, p)
		case !bytes.Equal(oldContent, newTree[p]):
			writes[p] = newTree[p]
			modified = append(modified, p)
		}
	}
	for _, p := range sortedKeys(oldTree) {
		if _, ok := newTree[p]; !ok {
			deleted = append(deleted, p)
		}
	}
	if !force {
		cs, err := conflicts(t.root, writes, deleted, oldTree)
		if err != nil {
			return fail(err)
		}
		if len(cs) > 0 {
			return fail(conflictError(cs))
		}
	}
	if err := commit(t.root, writes, deleted, newSHA); err != nil {
		return fail(err)
	}
	for _, p := range modified {
		fmt.Fprintf(out, "M %s\n", p)
	}
	for _, p := range added {
		fmt.Fprintf(out, "A %s\n", p)
	}
	for _, p := range deleted {
		fmt.Fprintf(out, "D %s\n", p)
	}
	io.WriteString(out, status(true, "updated to "+short(newSHA)))
	return nil
}

// Outdated implements `git scaffold outdated` (§38): resolve the configured
// ref and compare it with the lock. It modifies nothing.
func Outdated(dir string, out io.Writer) (outdated bool, err error) {
	t, err := load(dir)
	if err != nil {
		return false, err
	}
	locked, err := readLock(t.root)
	if err != nil {
		return false, err
	}
	if locked == "" {
		return false, fmt.Errorf("no %s; run `git scaffold apply` first", lockName)
	}
	resolved, err := t.src.ResolveRef(t.cfg.SourceRef)
	if err != nil {
		return false, err
	}
	if resolved == locked {
		io.WriteString(out, status(true, "up to date at "+locked))
		return false, nil
	}
	io.WriteString(out, status(false, "update available: "+locked+" → "+resolved))
	return true, nil
}
